### ISSUE TITLE
请问大佬cin,cout的id填的是群聊号吗

### ISSUE THREAD

**Issue by mengdeqian** [linsyking/ChatGPT-QQBot#2]
为什么我在群里发完消息之后显示
我在config里填的是
export const cin = {
    "type": "group",
    "id": "596***689"
}

export const cout = {
    "type": "private",
    "id": "596***689"
}

send failed: [Private: 596***689] 发送失败，请先添加对方为好友(16)

**Comment by linsyking** [comment]
private是指发给一个人，要把type改成group

**Comment by linsyking** [comment]
如果要传给一个人，id就是他qq号；如果是群，就填群号。

**Comment by mengdeqian** [comment]
懂了，谢谢
